
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dualKey
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true  #System.out으로 찍는 셀렉
#        format_sql: true
        default_batch_fetch_size: 100       #sql? IN ??? ?? ??
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace   #?? ???? ? ??? ?? (?, ?)? ???? ?
# -> ??? ?? ?? ?
